const QuestionBankList = [
    {
        'id': 1, 
        'question': 'What is a correct way to create a React component?', 
        'options': ['function App()', 'var App = () => {}', 'class App extends React.Component', 'All of the above'], 
        'answer': 'All of the above'
    }, 
    {
        'id': 2, 
        'question': 'Which command is used to check the status of a Git repository?', 
        'options': ['git check', 'git log', 'git status', 'git diff'], 
        'answer': 'git status'
    }, 
    {
        'id': 3, 
        'question': 'What is the output of print(2 ** 3)?', 
        'options': ['5', '6', '8', '9'], 
        'answer': '8'
    }, 
    {
        'id': 4, 
        'question': 'What does JSX stand for?', 
        'options': ['JavaScript XML', 'Java Syntax Extension', 'Java Source XML', 'JSON XML'], 
        'answer': 'JavaScript XML'
    }, 
    {
        'id': 5, 'question': 
        'Which of the following is a Python tuple?', 'options': ['[1, 2]', '{1, 2}', '(1, 2)', '<1, 2>'], 'answer': '(1, 2)'}, 
    {'id': 6, 'question': 'Sample question 6?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 7, 'question': 'Sample question 7?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 8, 'question': 'Sample question 8?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 9, 'question': 'Sample question 9?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 10, 'question': 'Sample question 10?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 11, 'question': 'Sample question 11?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 12, 'question': 'Sample question 12?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 13, 'question': 'Sample question 13?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 14, 'question': 'Sample question 14?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 15, 'question': 'Sample question 15?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 16, 'question': 'Sample question 16?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 17, 'question': 'Sample question 17?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 18, 'question': 'Sample question 18?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 19, 'question': 'Sample question 19?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 20, 'question': 'Sample question 20?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 21, 'question': 'Sample question 21?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 22, 'question': 'Sample question 22?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 23, 'question': 'Sample question 23?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 24, 'question': 'Sample question 24?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 25, 'question': 'Sample question 25?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 26, 'question': 'Sample question 26?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 27, 'question': 'Sample question 27?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 28, 'question': 'Sample question 28?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 29, 'question': 'Sample question 29?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 30, 'question': 'Sample question 30?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 31, 'question': 'Sample question 31?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 32, 'question': 'Sample question 32?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 33, 'question': 'Sample question 33?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 34, 'question': 'Sample question 34?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 35, 'question': 'Sample question 35?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 36, 'question': 'Sample question 36?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 37, 'question': 'Sample question 37?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 38, 'question': 'Sample question 38?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 39, 'question': 'Sample question 39?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 40, 'question': 'Sample question 40?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 41, 'question': 'Sample question 41?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 42, 'question': 'Sample question 42?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 43, 'question': 'Sample question 43?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 44, 'question': 'Sample question 44?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 45, 'question': 'Sample question 45?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 46, 'question': 'Sample question 46?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 47, 'question': 'Sample question 47?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 48, 'question': 'Sample question 48?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 49, 'question': 'Sample question 49?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 50, 'question': 'Sample question 50?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 51, 'question': 'Sample question 51?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 52, 'question': 'Sample question 52?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 53, 'question': 'Sample question 53?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 54, 'question': 'Sample question 54?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 55, 'question': 'Sample question 55?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 56, 'question': 'Sample question 56?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 57, 'question': 'Sample question 57?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 58, 'question': 'Sample question 58?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 59, 'question': 'Sample question 59?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 60, 'question': 'Sample question 60?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 61, 'question': 'Sample question 61?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 62, 'question': 'Sample question 62?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 63, 'question': 'Sample question 63?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 64, 'question': 'Sample question 64?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 65, 'question': 'Sample question 65?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 66, 'question': 'Sample question 66?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 67, 'question': 'Sample question 67?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 68, 'question': 'Sample question 68?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 69, 'question': 'Sample question 69?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 70, 'question': 'Sample question 70?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 71, 'question': 'Sample question 71?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 72, 'question': 'Sample question 72?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 73, 'question': 'Sample question 73?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 74, 'question': 'Sample question 74?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 75, 'question': 'Sample question 75?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 76, 'question': 'Sample question 76?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 77, 'question': 'Sample question 77?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 78, 'question': 'Sample question 78?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 79, 'question': 'Sample question 79?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 80, 'question': 'Sample question 80?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 81, 'question': 'Sample question 81?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 82, 'question': 'Sample question 82?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 83, 'question': 'Sample question 83?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 84, 'question': 'Sample question 84?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 85, 'question': 'Sample question 85?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 86, 'question': 'Sample question 86?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 87, 'question': 'Sample question 87?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 88, 'question': 'Sample question 88?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 89, 'question': 'Sample question 89?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 90, 'question': 'Sample question 90?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 91, 'question': 'Sample question 91?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 92, 'question': 'Sample question 92?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 93, 'question': 'Sample question 93?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 94, 'question': 'Sample question 94?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 95, 'question': 'Sample question 95?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 96, 'question': 'Sample question 96?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 97, 'question': 'Sample question 97?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 98, 'question': 'Sample question 98?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {'id': 99, 'question': 'Sample question 99?', 'options': ['Option A', 'Option B', 'Option C', 'Option D'], 'answer': 'Option A'}, 
    {
        'id': 100, 
        'question': 'Sample question 100?', 
        'options': ['Option A', 'Option B', 'Option C', 'Option D'], 
        'answer': 'Option A'
    }
];

export default QuestionBankList;